[build-system]
requires = ["setuptools >= 59.2.0", "setuptools_scm >= 6.2", "wheel >= 0.37.0"]
build-backend = "setuptools.build_meta"


[tool.setuptools_scm]


# https://docs.pytest.org/en/6.2.x/customize.html#pyproject-toml
[tool.pytest.ini_options]
addopts = "-v --cov=marvinquote"

[tool.coverage.run]
branch = true
source = ["marvinquote"]

[tool.coverage.report]
show_missing = true
