#!/usr/bin/env python
"""extract doc from a makefile"""

# ############################################################################
# #= BASIC USAGE
#
# .PHONY: help
# help: ## Display help message

import fileinput
import re

BOLD = "\033[1m"
UNDERLINE = "\033[4m"
SECTION_COLOR = "\033[93m"
RESET = "\033[0m"
COMMAND_COLOR = "\033[36m"

for line in fileinput.input():  # noqa: SIM115
    if m := re.match(r"#= (.+)", line):
        print(f"\n{BOLD}{UNDERLINE}{SECTION_COLOR}{m.group(1)}{RESET}")
    elif m := re.match(r"([-\s\w]+):.+?##\s+(.+)", line):
        print(f"{BOLD}{COMMAND_COLOR}{m.group(1):<20}{RESET}{m.group(2)}")
