name: Python CI/CD

on:
  pull_request:
    branches: [ "main" ]
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  call-ci-cd-workflow:
    name: ci-cd
    uses: biocommons/.github/.github/workflows/python-ci-cd.yml@6-consolidate-python-workflows
    with:
      run-deploy: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v') }}
    secrets: inherit
